### ISSUE TITLE
配套客户端代码提问

### ISSUE THREAD

**Issue by huangqingcheng** [xtaci/gonet#19]
此种架构的Server有没有配套的客户端代码，比如Cocos2d-X上使用的？

**Comment by xtaci** [comment]
没有配套代码，但封包很简单，可以自己模拟一个客户端。

**Comment by huangqingcheng** [comment]
另外一个问题，请问doc目录下的dot文件用什么工具能够打开？

**Comment by xtaci** [comment]
用graphviz可以打开
