### ISSUE TITLE
gonet1 design document

### ISSUE THREAD

**Issue by sharpner** [xtaci/gonet#24]
Hi there, no idea if it's possible for you, but it would be awesome if someone (or you) could provide an english translation of the readme....

Sorry that I can't request this in chinese!

謝謝

**Comment by xtaci** [comment]
well, it's gonna need some time. plan to add it later.

**Comment by sharpner** [comment]
awesome. Thank you.

**Comment by xtaci** [comment]
I suggest you move forward to https://github.com/gonet2,  currently I'm focusing on gonet2, it has better design comparing to gonet1, so I can arrange time better for translations and documentations of gonet2. 

After all, gonet1 is simple and the source code can be read easily.

Basically, if you go through source code under directory src/agent & src/hub you can fully understand the simple design of gonet1. 

Thanks for your suggestion.

**Comment by xtaci** [comment]
PS. If you can knew Actor Model, you can understand gonet1 smoothly

**Comment by sharpner** [comment]
thanks!
